spring.application.name=smartcommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/smartcommerce
spring.datasource.username=postgres
spring.datasource.password=manu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

