spring.application.name=smartcommerce

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

gemini.api.key=${GEMINI_API_KEY}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}