    spring.application.name=smartcommerce

    spring.datasource.url=jdbc:postgresql://localhost:5432/smartcommerce
    spring.datasource.username=postgres
    spring.datasource.password=manu

    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    server.port=8080

    gemini.api.key=${GEMINI_API_KEY}
    spring.data.redis.host=localhost
    spring.data.redis.port=6379
